- id: mypy-conda
  name: mypy-conda
  entry: mypy
  language: conda
  'types': [python]
  args: ["--ignore-missing-imports", "--scripts-are-modules"]
  require_serial: true
  additional_dependencies: []
